logging:
    level:
        jooq: trace
        org.blackdread.sqltojava: DEBUG

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#        username: root
#        password:
        url: jdbc:postgresql://localhost:5432/dvdrental
        username: postgres
        password: admin
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jooq:
        sql-dialect: postgres


application:
    reserved-keywords: classpath:reserved/keywords.json
    database-to-export: dvdrental
    ignored-table-names:
        - databasechangelog
        - databasechangeloglock
        - jhi_authority
        - jhi_user
        - jhi_user_authority
        - QRTZ_BLOB_TRIGGERS
        - QRTZ_CALENDARS
        - QRTZ_CRON_TRIGGERS
        - QRTZ_FIRED_TRIGGERS
        - QRTZ_JOB_DETAILS
        - QRTZ_LOCKS
        - QRTZ_PAUSED_TRIGGER_GRPS
        - QRTZ_SCHEDULER_STATE
        - QRTZ_SIMPLE_TRIGGERS
        - QRTZ_SIMPROP_TRIGGERS
        - QRTZ_TRIGGERS
    export:
        path: ./dvdrental-jdl.jh
        type: jdl
